server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    database: 0
    password: 123456
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_oauth?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: introcks1234
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    initialize: false
  jpa:
    hibernate: 
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    
logging.level.org.springframework.security: DEBUG
